config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'dashboard#index'

  resources :sessions
  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

  resources :courses
  resources :semesters

  resources :instructors
  resources :students
  get 'students/:id/units', to: 'students#units'
  get 'students/:id/times', to: 'students#times'

  resources :groups

  resources :subject_bases
  resources :subjects

  resources :results, except: [:index] do
    collection do
      put :updates
    end
  end

end

app/models/semester.rb
class Semester < ActiveRecord::Base
  enum semester: {
    first_half: 1,
    second_half: 2,
  }

  default_scope { order 'year DESC, semester DESC' }

  has_many :groups, dependent: :destroy
  has_many :subjects, dependent: :destroy

  validates :year, presence: true, uniqueness: { scope: :semester }
  validates :semester, presence: true, inclusion: { in: self.semesters }

  def to_s
    I18n.t(:'semester.year', year: year) + ', ' + I18n.t(:"semester.semesters.#{ semester }")
  end

  def self.now
    t = Time.zone.now
    s = t.month.between?(4, 9) ? 'first_half' : 'second_half'

    self.find_or_create_by year: t.year, semester: semesters[s]
  end
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_action :set_semester, only: [:show, :edit, :update, :destroy]

  # GET /semesters
  # GET /semesters.json
  def index
    @semesters = Semester.all
  end

  # GET /semesters/1
  # GET /semesters/1.json
  def show
    @groups = @semester.groups
    @subjects = @semester.subjects
  end

  # GET /semesters/new
  def new
    @semester = Semester.new
  end

  # GET /semesters/1/edit
  def edit
  end

  # POST /semesters
  # POST /semesters.json
  def create
    @semester = Semester.new(semester_params)

    respond_to do |format|
      if @semester.save
        format.html { redirect_to @semester, notice: 'Semester was successfully created.' }
        format.json { render :show, status: :created, location: @semester }
      else
        format.html { render :new }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semesters/1
  # PATCH/PUT /semesters/1.json
  def update
    respond_to do |format|
      if @semester.update(semester_params)
        format.html { redirect_to @semester, notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @semester }
      else
        format.html { render :edit }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semesters/1
  # DELETE /semesters/1.json
  def destroy
    @semester.destroy
    respond_to do |format|
      format.html { redirect_to semesters_url, notice: 'Semester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semester
      @semester = Semester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def semester_params
      params.require(:semester).permit(:year, :semester)
    end
end

app/views/semesters/_form.html.erb
<%= form_for(@semester) do |f| %>
  <% if @semester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@semester.errors.count, "error") %> prohibited this semester from being saved:</h2>

      <ul>
      <% @semester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label '年度' %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label '学期' %><br>
    <%= f.text_field :semester %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/semesters/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

<%= link_to '一覧', @semester %> |
<%= link_to '戻る', semesters_path %>

app/views/semesters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>年度・学期一覧</h1>

<table>
  <thead>
    <tr>
      <th>年度</th>
      <th>学期</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semesters.each do |semester| %>
      <tr>
        <td><%= semester.year %></td>
        <td><%= semester.semester %></td>
        <td><%= link_to '詳細', semester %></td>
        <td><%= link_to '編集', edit_semester_path(semester) %></td>
        <td><%= link_to '削除', semester, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_semester_path %>

app/views/semesters/new.html.erb
<h1>新規作成</h1>

<%= render 'form' %>

<%= link_to '戻る', semesters_path %>

app/views/semesters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>年度</strong>
  <%= @semester.year %>
</p>

<p>
  <strong>学期</strong>
  <%= @semester.semester %>
</p>

<% @groups.each do |group| %>
  <p><%= group.name %></p>
<% end %>

<% @subjects.each do |subject| %>
  <p><%= subject.name %></p>
<% end %>

<%= link_to '編集', edit_semester_path(@semester) %> |
<%= link_to '戻る', semesters_path %>