config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'dashboard#index'

  resources :sessions
  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

  resources :courses
  resources :semesters

  resources :instructors
  resources :students
  get 'students/:id/units', to: 'students#units'
  get 'students/:id/times', to: 'students#times'

  resources :groups

  resources :subject_bases
  resources :subjects

  resources :results, except: [:index] do
    collection do
      put :updates
    end
  end

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  authenticates_with_sorcery!

  after_initialize :set_defaults

  has_and_belongs_to_many :groups
  has_and_belongs_to_many :subjects

  validates :code, presence: true, uniqueness: true
  validates :name, presence: true
  validates :perms, presence: true,
    numericality: { greater_than_or_equal_to: 0, only_integer: true }


  with_options if: :new_record? do |record|
    record.validates :password, confirmation: true, length: { minimum: 8 }
    record.validates :password_confirmation, presence: true
  end

  def admin?
    (perms & 1) != 0
  end

  def to_s
    name
  end

  private def set_defaults
    perms ||= 0
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create]

  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name, :ruby, :perms, :password, :password_confirmation)
    end
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :code do %>講師ID<% end %>
    <%= f.text_field :code, class: 'form-control', disabled: params[:action] == 'edit' %>
  </div>

  <div class="form-group">
    <%= f.label :name do %>名前<% end %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password do %>
      新しいパスワード
    <% end %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation do %>
      新しいパスワードの確認
    <% end %>
    <%= f.text_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :crypted_password do %>
      現在のパスワード
    <% end %>
    <%= f.text_field :crypted_password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<% content_for :header do %><h1>編集</h1><% end %>
<%= render 'form' %>

app/views/instructors/index.html.erb
<% content_for :header do %>講師一覧<% end %>

<div class="panel panel-default">
  <table id="data" class="table table-bordered table-condensed">
    <thead>
      <tr>
        <th class="col-xs-1 code">
          <label class="control-label">講師ID</label>
          <div class="code-filter-area inline-form"></div>
        </th>
        <th class="col-xs-3 name">
          <label class="control-label">氏名(ふりがな)</label>
          <div class="name-filter-area inline-form"></div>
        </th>
        <th class="col-xs-4 classes">
          <label class="control-label">クラス</label>
          <div class="classes-filter-area inline-form"></div>
        </th>
        <th class="col-xs-4 subjects">
          <label class="control-label">教科</label>
          <div class="subjects-filter-area inline-form"></div>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @instructors.each do |instructor| %>
        <tr>
          <td class="col-xs-1 code">
            <%= link_to instructor.code, instructor %>
          </td>
          <td class="col-xs-3 name">
              <ruby>
                <rb><%= link_to instructor.name, instructor %></rb>
                <rp>(</rp>
                <rt><%= instructor.ruby %></rt>
                <rp>)</rp>
              </ruby>
            <% if current_user.admin? || current_user == instructor %>
              <%= link_to fa_edit_icon, edit_instructor_path(instructor),
                    class: 'btn btn-default btn-xs' %>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to fa_delete_icon, instructor,
                    method: :delete, data: { confirm: '本当に削除しますか?' },
                    class: 'btn btn-default btn-xs' %>
            <% end %>
          </td>
          <td class="col-xs-4 classes">
            <% instructor.groups.includes(:semester).where('semesters.year': current_semester.year).each do |g| %>
              <%= link_to g, class: ('btn btn-%s btn-xs' % [(g.semester == current_semester) ? 'primary' : 'default']) do %>
                <%= g.name %> <small>(<%= g.semester %>)</small>
              <% end %>
            <% end %>
          </td>
          <td class="col-xs-4 subjects">
            <% instructor.subjects.includes(:semester).where('semesters.year': current_semester.year).each do |s| %>
              <%= link_to s, class: ('btn btn-%s btn-xs' % [(s.semester == current_semester) ? 'primary' : 'default']) do %>
                <%= s.name %> <small><%= s.semester %></small>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="panel-footer">
    <%= link_to fa_new_icon, new_instructor_path, class: 'btn btn-primary center-block' %>
  </div>
</div>

<script>
$('table#data').exTableFilter({
  filters: [
    {
      append: {
        to: 'div.code-filter-area',
        type: 'text',
      },
    },
    {
      append: {
        to: 'div.name-filter-area',
        type: 'text',
      },
    },
    {
      append: {
        to: 'div.classes-filter-area',
        type: 'text',
      },
    },
    {
      append: {
        to: 'div.subjects-filter-area',
        type: 'text',
      },
    },
  ],
});
</script>

app/views/instructors/new.html.erb
<h1>講師登録</h1>

<%= render 'form' %>

<%= link_to '戻る', instructors_path %>

app/views/instructors/show.html.erb
<% content_for :header do %>
  <%= @instructor.code %>
  <small>
    <ruby>
      <rb><%= @instructor.name %></rb>
      <rp>(</rp>
      <rt><%= @instructor.ruby %></rt>
      <rp>)</rp>
    </ruby>
  </small>
<% end %>