config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'dashboard#index'

  resources :sessions
  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

  resources :courses
  resources :semesters

  resources :instructors
  resources :students
  get 'students/:id/units', to: 'students#units'
  get 'students/:id/times', to: 'students#times'

  resources :groups

  resources :subject_bases
  resources :subjects

  resources :results, except: [:index] do
    collection do
      put :updates
    end
  end

end

app/models/result.rb
class Result < ActiveRecord::Base
  enum status: ['takeable', 'passed', 'absented', 'stopped']

  default_scope { includes(:student).order('students.ruby, students.name') }

  after_initialize :set_defaults

  belongs_to :students_subject
  validates :students_subject, presence: true

  has_one :student, through: :students_subject
  has_one :subject, through: :students_subject

  validates :midterm, :termend, :resit, :final,
    allow_nil: true,
    numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 100,
      only_integer: true,
    }

  validates :midterm_status, :termend_status, :resit_status,
    allow_nil: true, inclusion: { in: self.statuses.values }

  private def set_defaults
    status ||= 0
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  load_and_authorize_resource

  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /results/updates.json
  def updates
    results_params = params.require(:results)

    respond_to do |format|
      format.json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:id, :student_subject_id, :midterm, :termend, :resit, :final, 
        :midterm_status, :termend_status, :resit_status, :final_status)
    end
end

app/views/results/_form.html.erb
<%= form_for([Subject.find(params[:subject_id]), @result]) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 名前 %><br>
    <%= f.text_field :students_subject_id %>
  </div>
  <div class="field">
    <%= f.label 前期 %><br>
    <%= f.number_field :midterm, in: 0..100 %>
  </div>
  <div class="field">
    <%= f.label 後期 %><br>
    <%= f.number_field :termend, in: 0..100 %>
  </div>
  <div class="field">
    <%= f.label 追再試 %><br>
    <%= f.number_field :resit, in: 0..100 %>
  </div>
  <div class="field">
    <%= f.label 最終 %><br>
    <%= f.number_field :final, in: 0..100 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/_table.html.erb
<table class="table table-bordered table-condensed table-hover table-striped">
  <thead>
    <tr>
      <th>名前</th>
      <th>前期</th>
      <th>後期</th>
      <th>追再試</th>
      <th>最終</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% results.each do |result| %>
      <tr>
        <td><%= result.students_subject %></td>
        <td><%= result.midterm %></td>
        <td><%= result.termend %></td>
        <td><%= result.resit %></td>
        <td><%= result.final %></td>
        <td><%= link_to '詳細', result_path(result) %></td>
<% if logged_in? and result.subject.instructors.include?(current_user) %>
        <td><%= link_to '編集', edit_result_path(result) %></td>
        <td><%= link_to '削除', result, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/results/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

<%= link_to '一覧', subject_result_path(@subject, @result) %> |
<%= link_to '戻る', subject_results_path(@subject) %>

app/views/results/index.html.erb
<h1>成績一覧</h1>

<%= render partial: 'table', locals: { results: @results, subject: @subject } %>

app/views/results/new.html.erb
<h1>新規作成</h1>

<%= render 'form' %>

<%= link_to '戻る', subject_results_path(@subject) %>

app/views/results/show.html.erb
<p>
  <strong>名前</strong>
  <%= @result.students_subject %>
</p>

<p>
  <strong>前期</strong>
  <%= @result.midterm %>
</p>

<p>
  <strong>後期</strong>
  <%= @result.termend %>
</p>

<p>
  <strong>追再試</strong>
  <%= @result.resit %>
</p>

<p>
  <strong>最終</strong>
  <%= @result.final %>
</p>

<%= link_to '編集', edit_result_path(@result) %> |
<%= link_to '戻る', results_path %>