config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'dashboard#index'

  resources :sessions
  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

  resources :courses
  resources :semesters

  resources :instructors
  resources :students
  get 'students/:id/units', to: 'students#units'
  get 'students/:id/times', to: 'students#times'

  resources :groups

  resources :subject_bases
  resources :subjects

  resources :results, except: [:index] do
    collection do
      put :updates
    end
  end

end

app/views/layouts/_dropdown.html.haml
%ul.dropdown-menu(role="menu")
  - items.each do |item|
    %li(role="presentation")
      = link_to item do
        = item.name
        %small= "(#{ item.semester })"
  - if items.any?
    %li.divider(role="presentation")
  %li(role="presentation")= link_to 'すべて表示', items_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield :title %>
    <% else %>
      Even
    <% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Even', root_path, class: 'navbar-brand' %>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <%= link_to groups_path, class: 'dropdown-toggle', role: 'button',
                    'aria-expanded': 'false', 'data-toggle': 'dropdown' do %>
              クラス
              <span class="caret"></span>
            <% end %>
            <%= dropdown_menu Group, groups_path %>
          </li>

          <li class="dropdown">
            <%= link_to subjects_path, class: 'dropdown-toggle', role: 'button',
                    'aria-expanded': 'false', 'data-toggle': 'dropdown' do %>
              教科
              <span class="caret"></span>
            <% end %>
            <%= dropdown_menu Subject, subject_bases_path %>
          </li>

          <li><%= link_to '学科一覧', courses_path %></li>
          <li><%= link_to '講師一覧', instructors_path %></li>
          <li><%= link_to '学生一覧', students_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to current_user.try(:code), current_user %></li>
            <li><%= link_to 'ログアウト', :logout, method: :post %></li>
          <% else %>
            <li><%= link_to 'サインアップ', new_instructor_path %></li>
            <li><%= link_to 'ログイン', :login %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="page-header">
      <h1>
        <% if content_for?(:header) -%>
          <%= yield :header %>
        <% else -%>
          Lorem ipsum
        <% end -%>
      </h1>
    </div>

    <% if flash[:error] %>
      <div class="alert alert-danger"><%= flash[:error] %></div>
    <% end %>
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>